### ISSUE TITLE
EAR failing to start when deployed on PCFDev

### ISSUE THREAD

**Issue by jbray-pvtl** [cloudfoundry-community/tomee-buildpack#30] opened 2018-01-18 17:19 UTC
When deploying an EAR file to a local PCFDev instance with the tomee-buildpack, the application fails to start with an exception, ClassNotFoundException, for the org.apache.activemq.ra.ActiveMQResourceAdapter class, although the class is included in the EAR.  Specifically, the class is included as a dependency in the WAR, since the error appears to be originating from the WAR.  Has anyone seen anything like this when deploying an EAR to cloud foundry using the tomee-buildpack?  The ear includes multiple EJBs and a WAR.

We were able to add the dependency to the tomee-buildpack by configuring the manifest.yml file to use the tomee-plus distribution, which includes the missing libraries.

**Comment by violetagg** [comment] 2018-01-18 17:23
Hi,

Can you provide the logs from the startup?
Where exactly is the jar with the class located in the WAR?
Is it reproducible on a local TomEE installation or just in the cloud?

Regards,
Violeta

**Comment by nebhale** [comment] 2018-01-18 17:24
It's exactly the same issue as #23.

**Comment by jbray-pvtl** [comment] 2018-01-19 14:40
I believe we may have found the reason for this exception.  The is a dependency in the deployed EAR for the org.apache.activemq.ra.ActiveMQResourceAdapter class however, the Tomee application server bundled with the tomee-buildpack uses it's own flavor of this class [org.apache.openejb.resource.activemq.ActiveMQResourceAdapter](https://github.com/apache/tomee/blob/master/container/openejb-core/src/main/java/org/apache/openejb/resource/activemq/ActiveMQResourceAdapter.java).  The required class is missing in the buildpack when we look at what is actually deployed.  We are now attempting to find out how to add this class to the the TomEE instance in without forking the buildpack.

**Comment by violetagg** [comment] 2018-01-23 19:49
That's because TomEE buildpack uses TomEE WebProfile and not TomEE plus/plume.
Here is what comes with both flavours
http://tomee.apache.org/javaee7-status.html

**Comment by violetagg** [comment] 2018-02-22 16:26
Closing this one. If you still have issues you can reopen it.

**Closed by violetagg** 2018-02-22 16:26 UTC
